# Generated by Django 5.2.8 on 2025-11-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tumblr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vimeo_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
